import { zodResolver } from "@hookform/resolvers/zod";
import { motion, useInView, useReducedMotion } from "motion/react";
import {
  ArrowRight,
  Award,
  Building2,
  Check,
  ChevronDown,
  Factory,
  Facebook,
  Gauge,
  Image as ImageIcon,
  Linkedin,
  Mail,
  MapPin,
  Menu,
  Phone,
  Settings,
  ShieldCheck,
  Wrench,
} from "lucide-react";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";

import { Button } from "@/components/ui/button";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Textarea } from "@/components/ui/textarea";
import { applications, contact, machineMenu, machines, navigation, processSteps, serviceNetwork, stats, type ImageAsset, type Machine } from "@/data/site";

const anchor = (label: string) => `#${label.toLowerCase().replaceAll(" & ", "-").replaceAll(" ", "-")}`;

function Reveal({ children, className = "" }: { children: ReactNode; className?: string }) {
  const reduceMotion = useReducedMotion();
  return <motion.div className={className} initial={reduceMotion ? false : { opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.14 }} transition={{ duration: 0.5, ease: "easeOut" }}>{children}</motion.div>;
}

function ImagePlaceholder({ image, className = "", eager = false }: { image: ImageAsset; className?: string; eager?: boolean }) {
  const ratio = image.ratio === "4/5" ? "aspect-[4/5]" : image.ratio === "16/10" ? "aspect-[16/10]" : "aspect-[4/3]";
  return (
    <div className={`placeholder-image group relative overflow-hidden rounded-lg ${ratio} ${className}`}>
      {image.src ? <img src={image.src} alt={image.alt} loading={eager ? "eager" : "lazy"} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.03]" /> : <div role="img" aria-label={image.alt} className="flex h-full w-full flex-col items-center justify-center gap-3 px-5 text-center"><ImageIcon className="h-7 w-7 text-brand" strokeWidth={1.5} /><span className="text-sm font-medium text-muted-foreground">{image.caption}</span></div>}
    </div>
  );
}

function SectionHeading({ label, title, intro, centered = false }: { label?: string; title: string; intro?: string; centered?: boolean }) {
  return <div className={centered ? "mx-auto max-w-3xl text-center" : "max-w-3xl"}>{label && <p className="section-label">{label}</p>}<h2 className="mt-3 font-display text-3xl font-bold leading-tight text-foreground md:text-4xl">{title}</h2>{intro && <p className="mt-4 text-base leading-7 text-muted-foreground md:text-lg">{intro}</p>}</div>;
}

export function Header() {
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 12); onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  return <>
    <div className="hidden border-b border-border bg-section md:block"><div className="site-container flex h-9 items-center justify-between text-xs text-muted-foreground"><span className="flex items-center gap-2"><MapPin className="h-3.5 w-3.5 text-brand" />{contact.address}</span><div className="flex items-center gap-5"><a href={`tel:${contact.sales.replaceAll(" ", "")}`}>Sales: {contact.sales}</a><a href={`mailto:${contact.email}`}>{contact.email}</a><a href="#linkedin" aria-label="LinkedIn"><Linkedin className="h-3.5 w-3.5" /></a><a href="#facebook" aria-label="Facebook"><Facebook className="h-3.5 w-3.5" /></a></div></div></div>
    <header className={`sticky top-0 z-40 bg-background transition-shadow ${scrolled ? "border-b border-border shadow-header" : "border-b border-transparent"}`}>
      <div className="site-container flex h-20 items-center justify-between gap-5">
        <a href="#top" className="flex min-w-0 items-center gap-2.5" aria-label="Akashganga home"><img src="/logo-icon-color.png" alt="" className="h-11 w-11 shrink-0" width={44} height={44} /><span className="max-w-40 font-display text-xs font-bold leading-tight text-foreground sm:max-w-52 sm:text-sm">Akashganga Constructional Machines</span></a>
        <nav className="hidden items-center gap-4 lg:flex" aria-label="Primary navigation">{navigation.map((item) => item === "Machines" ? <div className="group relative" key={item}><a href="#machines" className="nav-link flex items-center gap-1">Machines <ChevronDown className="h-3.5 w-3.5" /></a><div className="invisible absolute left-1/2 top-full w-64 -translate-x-1/2 pt-5 opacity-0 transition group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100"><div className="rounded-lg border border-border bg-background p-2 shadow-menu">{machineMenu.map((entry) => <a key={entry} href="#machines" className="block rounded-md px-3 py-2 text-sm text-muted-foreground hover:bg-section hover:text-primary">{entry}</a>)}</div></div></div> : <a key={item} href={item === "Home" ? "#top" : anchor(item)} className="nav-link">{item}</a>)}</nav>
        <div className="flex items-center gap-2"><Button asChild size="lg" className="hidden lg:inline-flex"><a href="#enquiry">Request a Quote</a></Button><Sheet><SheetTrigger asChild><Button variant="outline" size="icon" className="lg:hidden" aria-label="Open navigation"><Menu /></Button></SheetTrigger><SheetContent className="w-[88vw]"><SheetHeader className="text-left"><SheetTitle>Akashganga</SheetTitle><SheetDescription>Constructional Machines</SheetDescription></SheetHeader><nav className="mt-8 flex flex-col" aria-label="Mobile navigation">{navigation.map((item) => <a key={item} href={item === "Home" ? "#top" : anchor(item)} className="border-b border-border py-3 text-base font-medium text-foreground">{item}</a>)}</nav><Button asChild className="mt-8 w-full" size="lg"><a href="#enquiry">Request a Quote</a></Button></SheetContent></Sheet></div>
      </div>
    </header>
  </>;
}

export function Hero() {
  return <section id="top" className="overflow-hidden bg-background py-16 md:py-24 lg:py-28"><div className="site-container grid items-center gap-12 lg:grid-cols-[1.02fr_0.98fr]"><Reveal><p className="section-label">Patented VSI crusher technology</p><h1 className="mt-5 max-w-3xl font-display text-4xl font-bold leading-[1.08] text-foreground sm:text-5xl lg:text-6xl">Engineering the future of manufactured sand</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Akashganga designs and manufactures patented VSI crushers and artificial sand making machines in Satara, producing cubical, IS 383 grade sand that replaces river sand.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><a href="#enquiry">Request a Quote <ArrowRight /></a></Button><Button asChild variant="outline" size="lg"><a href="#machines">Explore Machines</a></Button></div><div className="mt-10 grid gap-4 border-t border-border pt-6 sm:grid-cols-3">{[[Award,"Patented technology"],[ShieldCheck,"IS 383 & IS 1542 compliant sand"],[Factory,"In-house design & manufacturing"]].map(([Icon,text]) => { const TrustIcon = Icon as typeof Award; return <div key={String(text)} className="flex items-start gap-2.5"><TrustIcon className="mt-0.5 h-5 w-5 shrink-0 text-brand" /><span className="text-sm font-semibold leading-5 text-foreground">{String(text)}</span></div>; })}</div></Reveal><Reveal className="relative mx-auto w-full max-w-2xl"><ImagePlaceholder eager image={{ alt: "Flagship VSI crusher or sand plant", caption: "Photo: flagship VSI crusher / sand plant", ratio: "4/3" }} /><div className="absolute -bottom-5 left-5 rounded-lg border border-border bg-background px-5 py-4 shadow-card"><span className="block text-xs font-semibold text-muted-foreground">Engineered throughput</span><strong className="mt-1 block font-display text-xl text-foreground">Capacity up to 250 TPH</strong></div></Reveal></div></section>;
}

function Counter({ value }: { value: string }) {
  const ref = useRef<HTMLSpanElement>(null); const visible = useInView(ref, { once: true }); const reduce = useReducedMotion(); const [display, setDisplay] = useState(value);
  useEffect(() => { if (!visible || reduce) return; const matches = value.match(/[\d,]+/g) ?? []; const nums = matches.map((part) => Number(part.replaceAll(",", ""))); let frame = 0; const total = 24; const timer = window.setInterval(() => { frame += 1; let i = 0; setDisplay(value.replace(/[\d,]+/g, () => { const target = nums[i] ?? 0; i += 1; return Math.round((target * frame) / total).toLocaleString("en-IN"); })); if (frame >= total) window.clearInterval(timer); }, 25); return () => window.clearInterval(timer); }, [visible, reduce, value]);
  return <span ref={ref}>{display}</span>;
}

export function StatsBar() { return <section aria-label="Company statistics" className="border-y border-border bg-background"><div className="site-container grid grid-cols-2 lg:grid-cols-4">{stats.map((stat, i) => <div key={stat.label} className={`px-4 py-8 text-center md:px-8 ${i % 2 ? "border-l border-border" : ""} ${i > 1 ? "border-t border-border lg:border-t-0" : ""} ${i > 0 ? "lg:border-l lg:border-border" : ""}`}><strong className="font-display text-2xl font-bold text-primary md:text-3xl"><Counter value={stat.value} />{stat.suffix}</strong><span className="mt-2 block text-sm leading-5 text-muted-foreground">{stat.label}</span></div>)}</div></section>; }

export function AboutSection() { const items = ["Well-equipped testing laboratory", "Modern design office and ERP systems", "Training centre for operators", "Team of 6 field service engineers"]; return <section id="about" className="section-space bg-background"><div className="site-container grid items-center gap-14 lg:grid-cols-2"><Reveal className="relative pb-14 pr-7 sm:pr-20"><ImagePlaceholder image={{ alt: "Akashganga manufacturing facility", caption: "Photo: Akashganga manufacturing facility", ratio: "4/5" }} className="max-w-md" /><ImagePlaceholder image={{ alt: "Akashganga testing laboratory", caption: "Photo: testing laboratory", ratio: "4/3" }} className="absolute bottom-0 right-0 w-[52%] border-8 border-background shadow-card" /></Reveal><Reveal><SectionHeading label="About Akashganga" title="Designed, manufactured and tested under one roof" /><p className="mt-6 text-base leading-8 text-muted-foreground md:text-lg">Our design department is led by experienced engineers who follow the performance of every machine we supply. We maintain a complete history of each machine in the field, and that knowledge drives constant improvement in our designs.</p><div className="mt-7 grid gap-4 sm:grid-cols-2">{items.map((item) => <div key={item} className="flex items-start gap-3"><span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-brand-soft"><Check className="h-3.5 w-3.5 text-primary" /></span><span className="text-sm font-semibold leading-6 text-foreground">{item}</span></div>)}</div><Button variant="outline" size="lg" className="mt-8">About the company <ArrowRight /></Button></Reveal></div></section>; }

export function MachineCard({ machine }: { machine: Machine }) { return <article className="group overflow-hidden rounded-lg border border-border bg-background transition duration-300 hover:-translate-y-1 hover:border-brand"><div className="relative overflow-hidden"><ImagePlaceholder image={machine.image} className="rounded-none border-0" />{machine.patented && <span className="absolute left-4 top-4 rounded-full bg-primary px-3 py-1 text-xs font-bold text-primary-foreground">Patented</span>}</div><div className="p-6"><h3 className="font-display text-xl font-bold text-foreground">{machine.title}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-muted-foreground">{machine.description}</p><div className="mt-5 flex min-h-14 flex-wrap content-start gap-2">{machine.specs.map((spec) => <span key={spec} className="rounded-full border border-border bg-section px-3 py-1 text-xs font-semibold text-foreground">{spec}</span>)}</div><a href="#enquiry" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-primary hover:text-primary-hover">View details <ArrowRight className="h-4 w-4" /></a></div></article>; }

export function MachinesSection() { return <section id="machines" className="section-space bg-section"><div className="site-container"><Reveal><SectionHeading label="Our machines" title="Machines for every stage of crushing" intro="From primary crushing to dry dust separation, our integrated range is engineered to produce consistent, specification-grade material." /></Reveal><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{machines.map((machine) => <Reveal key={machine.title}><MachineCard machine={machine} /></Reveal>)}</div><div className="mt-10 text-center"><Button variant="outline" size="lg">View all machines <ArrowRight /></Button></div></div></section>; }

export function FeatureRow({ icon: Icon, title, text }: { icon: typeof Gauge; title: string; text: string }) { return <div className="flex gap-4 border-b border-border py-5 first:pt-0 last:border-0 last:pb-0"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-md bg-brand-soft"><Icon className="h-5 w-5 text-primary" /></span><div><h3 className="font-display text-lg font-bold text-foreground">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div></div>; }

export function TechnologySection() { const features = [[Settings,"Oil lubrication system","Our VSI crushers use oil lubrication with cooling and filtration, where most manufacturers use grease. Bearings run cooler, cleaner and last longer."],[Gauge,"3.5% lower power cost","The rotating assembly runs on a film of oil, reducing friction losses."],[ShieldCheck,"Built-in safety interlocks","The machine will not start if there is a fault, and the panel shows the operator what to fix."],[Wrench,"Easy maintenance","Parts are designed to fit only one way, so your own operators can maintain the machine."]] as const; return <section id="technology-patents" className="section-space bg-background"><div className="site-container"><Reveal><SectionHeading title="Why leading crusher operators choose Akashganga" /></Reveal><div className="mt-12 grid items-center gap-12 lg:grid-cols-2"><Reveal><ImagePlaceholder image={{ alt: "VSI rotor and oil lubrication system close-up", caption: "Photo: VSI rotor / oil lubrication system close-up", ratio: "4/3" }} /></Reveal><Reveal>{features.map(([icon,title,text]) => <FeatureRow key={title} icon={icon} title={title} text={text} />)}</Reveal></div></div></section>; }

export function ProcessTimeline() { return <section className="section-space bg-section"><div className="site-container"><Reveal><SectionHeading centered title="From boulder to sand in five steps" /></Reveal><div className="relative mt-14 grid gap-8 md:grid-cols-5 md:gap-4"><div className="absolute left-5 top-5 h-[calc(100%-2.5rem)] w-px bg-brand md:left-[10%] md:right-[10%] md:top-5 md:h-px md:w-auto" />{processSteps.map((step,index) => <Reveal key={step.title} className="relative flex gap-5 md:block md:text-center"><span className="relative z-10 flex h-10 w-10 shrink-0 items-center justify-center rounded-full border-2 border-brand bg-background font-display text-sm font-bold text-primary md:mx-auto">{index + 1}</span><div className="md:mt-6"><h3 className="font-display text-base font-bold text-foreground">{step.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{step.text}</p></div></Reveal>)}</div></div></section>; }

export function ApplicationCard({ app }: { app: typeof applications[number] }) { return <article className="group overflow-hidden rounded-lg border border-border bg-background transition duration-300 hover:-translate-y-1 hover:border-brand"><ImagePlaceholder image={{ alt: `${app.title} application`, caption: `Photo: ${app.title} application`, ratio: "4/3" }} className="rounded-none" /><div className="p-5"><h3 className="font-display text-lg font-bold text-foreground">{app.title}</h3><div className="mt-4 flex flex-wrap gap-2">{app.tags.map((tag) => <span key={tag} className="rounded-full bg-section px-2.5 py-1 text-xs font-medium text-muted-foreground">{tag}</span>)}</div></div></article>; }

export function ApplicationsSection() { return <section className="section-space bg-background"><div className="site-container"><Reveal><SectionHeading centered title="Proven on every type of stone" /></Reveal><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{applications.map((app) => <Reveal key={app.title}><ApplicationCard app={app} /></Reveal>)}</div></div></section>; }

export function ComparisonTable() { const rows = ["Availability", "Consistency of grading", "Environmental impact", "Compliance with IS standards"]; return <section className="section-space bg-section"><div className="site-container grid gap-10 lg:grid-cols-[0.75fr_1.25fr]"><Reveal><SectionHeading title="Manufactured sand vs river sand" intro="A clear technical comparison helps project teams assess material quality and supply reliability." /><Button variant="outline" size="lg" className="mt-7">Download profitability report</Button></Reveal><Reveal><div className="overflow-hidden rounded-lg border border-border bg-background"><div className="grid grid-cols-[0.9fr_1fr_1fr] border-b border-border bg-brand-soft text-sm font-bold text-foreground"><span className="p-4">Criteria</span><span className="border-l border-border p-4">River sand</span><span className="border-l border-border p-4">Akashganga manufactured sand</span></div>{rows.map((row) => <div key={row} className="grid grid-cols-[0.9fr_1fr_1fr] border-b border-border text-sm last:border-0"><strong className="p-4 text-foreground">{row}</strong><span className="border-l border-border p-4 text-muted-foreground">[Content to confirm with client]</span><span className="border-l border-border p-4 text-muted-foreground">[Content to confirm with client]</span></div>)}</div></Reveal></div></section>; }

export function ClientsStrip() { const certificates = ["Patent certificate", "Trade mark registration", "IEC certificate", "[Certification]"]; return <><section className="border-b border-border bg-background py-14"><div className="site-container"><div className="flex flex-wrap items-center justify-between gap-5"><h2 className="font-display text-2xl font-bold text-foreground">Patents & certifications</h2><a href="#technology-patents" className="inline-flex items-center gap-2 text-sm font-bold text-primary">View patents & certificates <ArrowRight className="h-4 w-4" /></a></div><div className="mt-8 grid grid-cols-2 gap-4 md:grid-cols-4">{certificates.map((item) => <div key={item} className="flex min-h-24 items-center justify-center rounded-lg border border-border bg-section px-4 text-center text-sm font-semibold text-muted-foreground"><Award className="mr-2 h-5 w-5 text-brand" />{item}</div>)}</div></div></section><section className="section-space bg-background"><div className="site-container"><SectionHeading centered title="Trusted by crusher operators across India" /><div className="mt-10 grid grid-cols-2 gap-4 md:grid-cols-6">{Array.from({ length: 6 }, (_, i) => <div key={i} className="flex h-20 items-center justify-center rounded-lg border border-border bg-section text-xs font-semibold text-muted-foreground">[Client logo]</div>)}</div><div className="mx-auto mt-8 max-w-3xl rounded-lg border border-border border-l-4 border-l-brand bg-background p-7 text-center text-muted-foreground">[Client testimonial]</div></div></section></>; }

export function NetworkNews() { return <section id="news" className="section-space bg-section"><div className="site-container grid gap-12 lg:grid-cols-2"><Reveal><SectionHeading label="Support where it matters" title="Sales & service network" /><div className="mt-8 grid gap-3 sm:grid-cols-2">{serviceNetwork.map((item) => <div key={item.state} className="rounded-lg border border-border bg-background p-4"><div className="flex items-center gap-2 font-display font-bold text-foreground"><MapPin className="h-4 w-4 text-brand" />{item.state}</div><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.cities}</p></div>)}</div></Reveal><Reveal><SectionHeading label="Company updates" title="Latest news" /><div className="mt-8 space-y-4"><NewsCard title="New product: Dry fines separator for aggregates, sand and minerals" text="Fine dust raises the water-cement ratio and weakens concrete. This separator removes it without water." /><NewsCard title="Notice of Annual General Meeting" text="Company announcement and meeting notice." /></div></Reveal></div></section>; }

export function NewsCard({ title, text }: { title: string; text: string }) { return <article className="rounded-lg border border-border bg-background p-6 transition hover:-translate-y-0.5 hover:border-brand"><span className="text-xs font-bold text-primary">NEWS</span><h3 className="mt-2 font-display text-lg font-bold leading-7 text-foreground">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p><a href="#news" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-primary">Read update <ArrowRight className="h-4 w-4" /></a></article>; }

const enquirySchema = z.object({ name: z.string().min(2, "Please enter your name"), company: z.string(), phone: z.string().min(8, "Please enter a valid phone number"), email: z.string().email("Please enter a valid email").or(z.literal("")), machine: z.string().min(1, "Please select a machine"), capacity: z.string(), stone: z.string(), message: z.string() });
type EnquiryValues = z.infer<typeof enquirySchema>;

export function EnquiryForm() { const [sent, setSent] = useState(false); const form = useForm<EnquiryValues>({ resolver: zodResolver(enquirySchema), defaultValues: { name: "", company: "", phone: "", email: "", machine: "", capacity: "", stone: "", message: "" } }); const submit = () => setSent(true); if (sent) return <div role="status" className="flex min-h-96 flex-col items-center justify-center rounded-lg bg-brand-soft p-8 text-center"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-primary"><Check className="h-7 w-7 text-primary-foreground" /></span><h3 className="mt-5 font-display text-2xl font-bold text-foreground">Enquiry ready</h3><p className="mt-2 max-w-sm text-sm leading-6 text-muted-foreground">Thank you. This approval prototype has validated your enquiry successfully.</p><Button variant="outline" className="mt-6" onClick={() => { setSent(false); form.reset(); }}>Send another enquiry</Button></div>; return <Form {...form}><form onSubmit={form.handleSubmit(submit)} className="grid gap-5 sm:grid-cols-2">{[["name","Name*"],["company","Company"],["phone","Phone*"],["email","Email"],["capacity","Required capacity (TPH)"],["stone","Stone type"]].map(([name,label]) => <FormField key={name} control={form.control} name={name as keyof EnquiryValues} render={({ field }) => <FormItem><FormLabel>{label}</FormLabel><FormControl><Input {...field} /></FormControl><FormMessage /></FormItem>} />)}<FormField control={form.control} name="machine" render={({ field }) => <FormItem className="sm:col-span-2"><FormLabel>Machine of interest*</FormLabel><Select onValueChange={field.onChange} value={field.value}><FormControl><SelectTrigger><SelectValue placeholder="Select a machine" /></SelectTrigger></FormControl><SelectContent>{machines.map((machine) => <SelectItem value={machine.title} key={machine.title}>{machine.title}</SelectItem>)}</SelectContent></Select><FormMessage /></FormItem>} /><FormField control={form.control} name="message" render={({ field }) => <FormItem className="sm:col-span-2"><FormLabel>Message</FormLabel><FormControl><Textarea rows={4} {...field} /></FormControl><FormMessage /></FormItem>} /><Button type="submit" size="lg" className="sm:col-span-2">Send Enquiry <ArrowRight /></Button></form></Form>; }

export function EnquirySection() { return <section id="enquiry" className="section-space bg-background"><div className="site-container"><div className="overflow-hidden rounded-xl border border-border border-t-4 border-t-brand bg-background shadow-card"><div className="grid lg:grid-cols-[0.8fr_1.2fr]"><div className="bg-section p-7 md:p-12"><SectionHeading label="Project enquiry" title="Tell us about your project" /><p className="mt-5 text-base leading-7 text-muted-foreground">Share your stone type and required output. Our sales team will recommend the right machine and reply within 24 hours.</p><div className="mt-8 space-y-4 text-sm">{[[Phone,"Sales",contact.sales],[Wrench,"Service",contact.service],[Building2,"Office",contact.office],[Mail,"Email",contact.email]].map(([Icon,label,value]) => { const ContactIcon = Icon as typeof Phone; return <div key={String(label)} className="flex items-start gap-3"><ContactIcon className="mt-0.5 h-4 w-4 text-primary" /><div><span className="block font-bold text-foreground">{String(label)}</span><span className="text-muted-foreground">{String(value)}</span></div></div>; })}</div></div><div className="p-7 md:p-12"><EnquiryForm /></div></div></div></div></section>; }

export function Footer() { return <footer id="contact" className="bg-footer text-footer-foreground"><div className="site-container grid gap-10 py-14 sm:grid-cols-2 lg:grid-cols-4"><div><div className="flex items-center gap-2.5"><img src="/logo-mark-white.png" alt="" className="h-14 w-14 shrink-0" width={56} height={56} /><span className="font-display text-xl font-bold">Akashganga</span></div><p className="mt-4 text-sm leading-6 text-footer-muted">Manufacturer of patented VSI crushers, artificial sand making machines and dust separation equipment.</p><p className="mt-4 text-sm leading-6 text-footer-muted">{contact.address}</p></div><FooterLinks title="Machines" links={machineMenu.slice(0,6)} /><FooterLinks title="Company" links={["About", "Technology & Patents", "Profitability", "Gallery", "Careers", "FAQs", "Contact"]} /><div><h3 className="font-display font-bold">Contact</h3><div className="mt-4 space-y-3 text-sm text-footer-muted"><a className="block hover:text-brand" href={`tel:${contact.sales.replaceAll(" ", "")}`}>Sales: {contact.sales}</a><a className="block hover:text-brand" href={`mailto:${contact.email}`}>{contact.email}</a><div className="flex gap-4 pt-2"><a href="#linkedin" aria-label="LinkedIn"><Linkedin className="h-5 w-5" /></a><a href="#facebook" aria-label="Facebook"><Facebook className="h-5 w-5" /></a></div></div></div></div><div className="border-t border-footer-border"><div className="site-container flex flex-col justify-between gap-3 py-5 text-xs text-footer-muted sm:flex-row"><span>© 2026 Akashganga Constructional Machines Pvt. Ltd. All rights reserved.</span><a href="#privacy">Privacy Policy</a></div></div></footer>; }
function FooterLinks({ title, links }: { title: string; links: readonly string[] }) { return <div><h3 className="font-display font-bold">{title}</h3><ul className="mt-4 space-y-2.5">{links.map((link) => <li key={link}><a href={anchor(link)} className="text-sm text-footer-muted hover:text-brand">{link}</a></li>)}</ul></div>; }

export function HomePage() { return <div className="min-h-screen bg-background"><Header /><main><Hero /><StatsBar /><AboutSection /><MachinesSection /><TechnologySection /><ProcessTimeline /><ApplicationsSection /><ComparisonTable /><ClientsStrip /><NetworkNews /><EnquirySection /></main><Footer /><a href={contact.whatsapp} target="_blank" rel="noreferrer" aria-label="Contact Akashganga on WhatsApp" className="fixed bottom-5 right-5 z-30 flex h-14 w-14 items-center justify-center rounded-full bg-whatsapp text-whatsapp-foreground shadow-float transition-transform hover:-translate-y-1 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"><Phone className="h-6 w-6" /></a></div>; }