import { motion, useInView, useReducedMotion } from "motion/react";
import { RiArrowDownSLine, RiArrowRightLine, RiAwardFill, RiBuilding2Fill, RiBuilding4Fill, RiCheckLine, RiDashboard3Fill, RiDropFill, RiFacebookFill, RiFilePdf2Fill, RiFlashlightFill, RiImageLine, RiLinkedinFill, RiMailFill, RiMapPin2Fill, RiMenu3Line, RiPhoneFill, RiShieldCheckFill, RiToolsFill, RiVerifiedBadgeFill, RiWhatsappFill } from "react-icons/ri";
import type { IconType } from "react-icons";
import { useEffect, useRef, useState, type ReactNode } from "react";

import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { EnquiryForm } from "@/components/enquiry-form";
import { NetworkMap } from "@/components/network-map";
import { ProcessDiagram } from "@/components/process-diagram";
import { applications, contact, heroVideo, images, machineMenu, machines, navigation, stats, type ImageAsset, type Machine } from "@/data/site";

const anchor = (label: string) => `#${label.toLowerCase().replaceAll(" & ", "-").replaceAll(" ", "-")}`;

function Reveal({ children, className = "" }: { children: ReactNode; className?: string }) {
  const reduceMotion = useReducedMotion();
  return <motion.div className={className} initial={reduceMotion ? false : { opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.14 }} transition={{ duration: 0.5, ease: "easeOut" }}>{children}</motion.div>;
}

function ImagePlaceholder({ image, className = "", eager = false, shade = false }: { image: ImageAsset; className?: string; eager?: boolean; shade?: boolean }) {
  const ratio = image.ratio === "4/5" ? "aspect-[4/5]" : image.ratio === "16/10" ? "aspect-[16/10]" : "aspect-[4/3]";
  return (
    <div className={`placeholder-image group relative overflow-hidden rounded-lg ${ratio} ${className}`}>{image.src && shade && <div aria-hidden className="pointer-events-none absolute inset-0 z-10 bg-gradient-to-t from-foreground/35 via-transparent to-transparent" />}
      {image.src ? <img src={image.src} alt={image.alt} loading={eager ? "eager" : "lazy"} className="h-full w-full object-cover transition-transform duration-700 ease-out group-hover:scale-[1.05]" /> : <div role="img" aria-label={image.alt} className="flex h-full w-full flex-col items-center justify-center gap-3 px-5 text-center"><RiImageLine className="h-7 w-7 text-brand" /><span className="text-sm font-medium text-muted-foreground">{image.caption}</span></div>}
    </div>
  );
}

function SectionHeading({ label, title, intro, centered = false }: { label?: string; title: string; intro?: string; centered?: boolean }) {
  return <div className={centered ? "mx-auto max-w-3xl text-center" : "max-w-3xl"}>{label && <p className="section-label">{label}</p>}<h2 className="mt-3 font-display text-3xl font-bold leading-tight text-foreground md:text-4xl">{title}</h2>{intro && <p className="mt-4 text-base leading-7 text-muted-foreground md:text-lg">{intro}</p>}</div>;
}

export function Header() {
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 12); onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  return <>
    <div className="hidden border-b border-border bg-section md:block"><div className="site-container flex h-9 items-center justify-between text-xs text-muted-foreground"><span className="flex items-center gap-2"><RiMapPin2Fill className="h-3.5 w-3.5 text-brand" />{contact.address}</span><div className="flex items-center gap-5"><a href={`tel:${contact.sales.replaceAll(" ", "")}`}>Sales: {contact.sales}</a><a href={`mailto:${contact.email}`}>{contact.email}</a><a href="#linkedin" aria-label="LinkedIn" className="transition hover:-translate-y-0.5 hover:text-brand"><RiLinkedinFill className="h-3.5 w-3.5" /></a><a href="#facebook" aria-label="Facebook" className="transition hover:-translate-y-0.5 hover:text-brand"><RiFacebookFill className="h-3.5 w-3.5" /></a></div></div></div>
    <header className={`sticky top-0 z-40 bg-background transition-shadow ${scrolled ? "border-b border-border shadow-header" : "border-b border-transparent"}`}>
      <div className="site-container flex h-20 items-center justify-between gap-5">
        <a href="#top" className="flex min-w-0 items-center gap-2.5" aria-label="Akashganga home"><img src="/logo-icon-color.png" alt="" className="h-11 w-11 shrink-0" width={44} height={44} /><span className="flex flex-col font-display leading-tight"><span className="text-lg font-extrabold text-foreground sm:text-xl">Akashganga</span><span className="text-[0.65rem] font-semibold uppercase tracking-[0.12em] text-muted-foreground sm:text-xs">Constructional Machines</span></span></a>
        <nav className="hidden items-center gap-4 lg:flex xl:gap-6" aria-label="Primary navigation">{navigation.map((item) => item === "Machines" ? <div className="group relative" key={item}><a href="#machines" className="nav-link flex items-center gap-1">Machines <RiArrowDownSLine className="h-3.5 w-3.5 transition-transform duration-300 group-hover:rotate-180" /></a><div className="invisible absolute left-1/2 top-full w-64 -translate-x-1/2 pt-5 opacity-0 transition group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100"><div className="rounded-lg border border-border bg-background p-2 shadow-menu">{machineMenu.map((entry) => <a key={entry} href="#machines" className="block rounded-md px-3 py-2 text-sm text-muted-foreground transition-all duration-200 hover:bg-section hover:pl-4 hover:text-primary">{entry}</a>)}</div></div></div> : <a key={item} href={item === "Home" ? "#top" : anchor(item)} className="nav-link">{item}</a>)}</nav>
        <div className="flex items-center gap-2"><Button asChild size="lg" className="hidden lg:inline-flex"><a href="#enquiry">Request a Quote</a></Button><Sheet><SheetTrigger asChild><Button variant="outline" size="icon" className="lg:hidden" aria-label="Open navigation"><RiMenu3Line /></Button></SheetTrigger><SheetContent className="w-[88vw]"><SheetHeader className="text-left"><SheetTitle>Akashganga</SheetTitle><SheetDescription>Constructional Machines</SheetDescription></SheetHeader><nav className="mt-8 flex flex-col" aria-label="Mobile navigation">{navigation.map((item) => <a key={item} href={item === "Home" ? "#top" : anchor(item)} className="border-b border-border py-3 text-base font-medium text-foreground">{item}</a>)}</nav><Button asChild className="mt-8 w-full" size="lg"><a href="#enquiry">Request a Quote</a></Button></SheetContent></Sheet></div>
      </div>
    </header>
  </>;
}

export function Hero() {
  const reduceMotion = useReducedMotion();
  return (
    <section id="top" className="relative overflow-hidden bg-background">
      <div className="relative h-80 sm:h-[28rem] lg:absolute lg:inset-y-0 lg:right-0 lg:h-auto lg:w-[64%]">
        {heroVideo && !reduceMotion ? (
          <video className="h-full w-full object-cover" src={heroVideo} poster={images.hero} autoPlay muted loop playsInline aria-hidden />
        ) : (
          <img src={images.hero} alt="Sand manufacturing plant with conveyors and stockpiles" className="h-full w-full object-cover object-[60%_center]" fetchPriority="high" />
        )}
        <div aria-hidden className="absolute inset-0 bg-gradient-to-t from-background via-background/0 to-background/0 lg:bg-gradient-to-r lg:from-background lg:from-5% lg:via-background/60 lg:via-30% lg:to-transparent lg:to-65%" />
        <div className="absolute right-4 top-4 flex items-center gap-2 rounded-full bg-background/95 px-3.5 py-1.5 text-xs font-bold text-foreground shadow-card lg:right-10 lg:top-10"><span className="h-2 w-2 rounded-full bg-brand" />DFP dust free product technology</div>
        <div className="absolute bottom-4 left-4 flex items-center gap-4 rounded-lg border border-border bg-background px-4 py-3 shadow-card sm:px-5 sm:py-4 lg:bottom-10 lg:left-auto lg:right-10"><span className="hidden h-11 w-11 items-center justify-center rounded-lg bg-brand-soft sm:flex"><RiDashboard3Fill className="h-5 w-5 text-primary" /></span><div><span className="block text-xs font-semibold text-muted-foreground">Engineered throughput</span><strong className="mt-0.5 block font-display text-lg text-foreground sm:text-xl">Capacity up to 250 TPH</strong></div></div>
      </div>
      <div className="site-container relative py-12 md:py-16 lg:flex lg:min-h-[42rem] lg:items-center lg:py-24">
        <Reveal className="max-w-xl lg:max-w-[34rem] xl:max-w-xl"><p className="section-label">Patented VSI crusher technology</p><h1 className="mt-5 font-display text-4xl font-bold leading-[1.06] text-foreground sm:text-5xl xl:text-6xl">Engineering the future of manufactured sand</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">Akashganga designs and manufactures patented VSI crushers and artificial sand making machines in Satara, producing cubical, IS 383 grade sand that replaces river sand.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><a href="#enquiry">Request a Quote <RiArrowRightLine className="nudge" /></a></Button><Button asChild variant="outline" size="lg" className="bg-background"><a href="#machines">Explore Machines</a></Button></div><div className="mt-10 grid gap-4 border-t border-border pt-6 sm:grid-cols-3">{[[RiVerifiedBadgeFill,"Patented technology"],[RiShieldCheckFill,"IS 383 & IS 1542 compliant sand"],[RiBuilding4Fill,"In-house design & manufacturing"]].map(([Icon,text]) => { const TrustIcon = Icon as IconType; return <div key={String(text)} className="flex items-start gap-2.5"><TrustIcon className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><span className="text-sm font-semibold leading-5 text-foreground">{String(text)}</span></div>; })}</div></Reveal>
      </div>
    </section>
  );
}

function Counter({ value }: { value: string }) {
  const ref = useRef<HTMLSpanElement>(null); const visible = useInView(ref, { once: true }); const reduce = useReducedMotion(); const [display, setDisplay] = useState(value);
  useEffect(() => { if (!visible || reduce) return; const matches = value.match(/[\d,]+/g) ?? []; const nums = matches.map((part) => Number(part.replaceAll(",", ""))); let frame = 0; const total = 24; const timer = window.setInterval(() => { frame += 1; let i = 0; setDisplay(value.replace(/[\d,]+/g, () => { const target = nums[i] ?? 0; i += 1; return Math.round((target * frame) / total).toLocaleString("en-IN"); })); if (frame >= total) window.clearInterval(timer); }, 25); return () => window.clearInterval(timer); }, [visible, reduce, value]);
  return <span ref={ref}>{display}</span>;
}

export function StatsBar() { return <section aria-label="Company statistics" className="border-y border-border bg-background"><div className="site-container grid grid-cols-2 lg:grid-cols-4">{stats.map((stat, i) => <div key={stat.label} className={`px-4 py-8 text-center md:px-8 ${i % 2 ? "border-l border-border" : ""} ${i > 1 ? "border-t border-border lg:border-t-0" : ""} ${i > 0 ? "lg:border-l lg:border-border" : ""}`}><strong className="font-display text-2xl font-bold text-primary md:text-3xl"><Counter value={stat.value} />{stat.suffix}</strong><span className="mt-2 block text-sm leading-5 text-muted-foreground">{stat.label}</span></div>)}</div></section>; }

export function AboutSection() { const items = ["Well-equipped testing laboratory", "Modern design office and ERP systems", "Training centre for operators", "Team of 6 field service engineers"]; return <section id="about" className="section-space bg-background"><div className="site-container grid items-center gap-14 lg:grid-cols-2"><Reveal className="relative pb-14 pr-7 sm:pr-20"><ImagePlaceholder image={{ src: images.aboutFactory, alt: "Akashganga manufacturing facility", caption: "Photo: Akashganga manufacturing facility", ratio: "4/5" }} className="max-w-md" /><div className="absolute bottom-0 right-0 w-[52%] rounded-xl bg-background p-2 shadow-card"><ImagePlaceholder image={{ src: images.aboutLab, alt: "Akashganga testing laboratory", caption: "Photo: testing laboratory", ratio: "4/3" }} /></div><div className="absolute left-5 top-5 rounded-lg bg-background/95 px-4 py-3 shadow-card"><strong className="block font-display text-2xl font-bold text-primary">6,000 m²</strong><span className="text-xs font-semibold text-muted-foreground">Manufacturing facility, Satara</span></div></Reveal><Reveal><SectionHeading label="About Akashganga" title="Designed, manufactured and tested under one roof" /><p className="mt-6 text-base leading-8 text-muted-foreground md:text-lg">Our design department is led by experienced engineers who follow the performance of every machine we supply. We maintain a complete history of each machine in the field, and that knowledge drives constant improvement in our designs.</p><div className="mt-7 grid gap-4 sm:grid-cols-2">{items.map((item) => <div key={item} className="flex items-start gap-3"><span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-brand-soft"><RiCheckLine className="h-3.5 w-3.5 text-primary" /></span><span className="text-sm font-semibold leading-6 text-foreground">{item}</span></div>)}</div><Button variant="outline" size="lg" className="mt-8">About the company <RiArrowRightLine className="nudge" /></Button></Reveal></div></section>; }

export function MachineCard({ machine, index }: { machine: Machine; index: number }) {
  return (
    <article className="card-hover group flex h-full flex-col overflow-hidden rounded-lg border border-border bg-background">
      <div className="relative overflow-hidden"><ImagePlaceholder shade image={machine.image} className="rounded-none border-0" /><span className="absolute bottom-4 right-4 z-20 font-display text-sm font-bold text-white/90">{String(index + 1).padStart(2, "0")}</span>{machine.patented && <span className="absolute left-4 top-4 z-20 rounded-full bg-primary px-3 py-1 text-xs font-bold text-primary-foreground">Patented</span>}</div>
      <div className="flex flex-1 flex-col p-6">
        <h3 className="font-display text-xl font-bold text-foreground transition-colors group-hover:text-primary">{machine.title}</h3>
        <p className="mt-3 text-sm leading-6 text-muted-foreground">{machine.description}</p>
        <dl className="mt-5 divide-y divide-border border-y border-border text-sm">{machine.specs.map((spec) => <div key={spec.label} className="flex items-baseline justify-between gap-4 py-2.5"><dt className="text-muted-foreground">{spec.label}</dt><dd className={`text-right font-semibold ${spec.value.startsWith("[") ? "text-muted-foreground" : "text-foreground"}`}>{spec.value}</dd></div>)}</dl>
        <div className="mt-auto flex items-center justify-between gap-4 pt-6"><a href="#enquiry" className="hover-nudge inline-flex items-center gap-2 text-sm font-bold text-primary hover:text-primary-hover">View details <RiArrowRightLine className="nudge h-4 w-4" /></a><a href={machine.brochure} className="inline-flex items-center gap-1.5 text-sm font-semibold text-muted-foreground hover:text-primary"><RiFilePdf2Fill className="h-4 w-4" />Brochure (PDF)</a></div>
      </div>
    </article>
  );
}

export function MachinesSection() { return <section id="machines" className="section-space bg-section"><div className="site-container"><Reveal><SectionHeading label="Our machines" title="Machines for every stage of crushing" intro="From primary crushing to dry dust separation, our integrated range is engineered to produce consistent, specification-grade material." /></Reveal><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{machines.map((machine, index) => <Reveal key={machine.title} className="h-full"><MachineCard machine={machine} index={index} /></Reveal>)}</div><div className="mt-10 text-center"><Button variant="outline" size="lg">View all machines <RiArrowRightLine className="nudge" /></Button></div></div></section>; }

export function FeatureRow({ icon: Icon, title, text }: { icon: IconType; title: string; text: string }) { return <div className="group flex gap-4 border-b border-border py-5 first:pt-0 last:border-0 last:pb-0"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg bg-brand-soft text-primary transition-all duration-300 group-hover:-rotate-6 group-hover:bg-primary group-hover:text-primary-foreground group-hover:shadow-button"><Icon className="h-6 w-6" /></span><div><h3 className="font-display text-lg font-bold text-foreground transition-colors group-hover:text-primary">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div></div>; }

export function TechnologySection() { const features = [[RiDropFill,"Oil lubrication system","Our VSI crushers use oil lubrication with cooling and filtration, where most manufacturers use grease. Bearings run cooler, cleaner and last longer."],[RiFlashlightFill,"3.5% lower power cost","The rotating assembly runs on a film of oil, reducing friction losses."],[RiShieldCheckFill,"Built-in safety interlocks","The machine will not start if there is a fault, and the panel shows the operator what to fix."],[RiToolsFill,"Easy maintenance","Parts are designed to fit only one way, so your own operators can maintain the machine."]] as const; return <section id="technology-patents" className="section-space bg-background"><div className="site-container"><Reveal><SectionHeading title="Why leading crusher operators choose Akashganga" /></Reveal><div className="mt-12 grid items-center gap-12 lg:grid-cols-2"><Reveal className="relative"><ImagePlaceholder shade image={{ src: images.techRotor, alt: "VSI rotor and oil lubrication system close-up", caption: "Photo: VSI rotor / oil lubrication system close-up", ratio: "4/3" }} /><div className="absolute bottom-5 left-5 right-5 z-20 flex items-center justify-between gap-4 rounded-lg bg-background/95 px-5 py-4 shadow-card"><div><span className="block text-xs font-semibold text-muted-foreground">Patented rotor assembly</span><strong className="block font-display text-lg text-foreground">Oil lubricated, not grease</strong></div><span className="font-display text-2xl font-bold text-primary">−3.5%</span></div></Reveal><Reveal>{features.map(([icon,title,text]) => <FeatureRow key={title} icon={icon} title={title} text={text} />)}</Reveal></div></div></section>; }

export function ProcessTimeline() { return <section className="section-space bg-section"><div className="site-container"><Reveal><SectionHeading centered label="How it works" title="From boulder to sand in five steps" intro="Select a stage to see what happens to the stone as it moves through an Akashganga plant." /></Reveal><Reveal className="mt-12"><ProcessDiagram /></Reveal></div></section>; }

export function ApplicationCard({ app }: { app: typeof applications[number] }) { return <article className="card-hover group h-full overflow-hidden rounded-lg border border-border bg-background"><ImagePlaceholder image={{ src: app.image, alt: `${app.title} application`, caption: `Photo: ${app.title} application`, ratio: "4/3" }} className="rounded-none" /><div className="p-5"><h3 className="font-display text-lg font-bold text-foreground transition-colors group-hover:text-primary">{app.title}</h3><div className="mt-4 flex flex-wrap gap-2">{app.tags.map((tag) => <span key={tag} className="rounded-full bg-section px-2.5 py-1 text-xs font-medium text-muted-foreground transition-colors group-hover:bg-brand-soft group-hover:text-foreground">{tag}</span>)}</div></div></article>; }

export function ApplicationsSection() { return <section className="section-space bg-background"><div className="site-container"><Reveal><SectionHeading centered title="Proven on every type of stone" /></Reveal><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{applications.map((app) => <Reveal key={app.title} className="h-full"><ApplicationCard app={app} /></Reveal>)}</div></div></section>; }

export function ComparisonTable() { const rows = ["Availability", "Consistency of grading", "Environmental impact", "Compliance with IS standards"]; return <section className="section-space bg-section"><div className="site-container grid gap-10 lg:grid-cols-[0.75fr_1.25fr]"><Reveal><SectionHeading title="Manufactured sand vs river sand" intro="A clear technical comparison helps project teams assess material quality and supply reliability." /><Button variant="outline" size="lg" className="mt-7">Download profitability report</Button></Reveal><Reveal><div className="overflow-hidden rounded-lg border border-border bg-background"><div className="grid grid-cols-[0.9fr_1fr_1fr] border-b border-border bg-brand-soft text-sm font-bold text-foreground"><span className="p-4">Criteria</span><span className="border-l border-border p-4">River sand</span><span className="border-l border-border p-4">Akashganga manufactured sand</span></div>{rows.map((row) => <div key={row} className="grid grid-cols-[0.9fr_1fr_1fr] border-b border-border text-sm last:border-0"><strong className="p-4 text-foreground">{row}</strong><span className="border-l border-border p-4 text-muted-foreground">[Content to confirm with client]</span><span className="border-l border-border p-4 text-muted-foreground">[Content to confirm with client]</span></div>)}</div></Reveal></div></section>; }

export function ClientsStrip() { const certificates = ["Patent certificate", "Trade mark registration", "IEC certificate", "[Certification]"]; return <><section className="border-b border-border bg-background py-14"><div className="site-container"><div className="flex flex-wrap items-center justify-between gap-5"><h2 className="font-display text-2xl font-bold text-foreground">Patents & certifications</h2><a href="#technology-patents" className="hover-nudge inline-flex items-center gap-2 text-sm font-bold text-primary">View patents & certificates <RiArrowRightLine className="nudge h-4 w-4" /></a></div><div className="mt-8 grid grid-cols-2 gap-4 md:grid-cols-4">{certificates.map((item) => <div key={item} className="card-hover group flex min-h-24 items-center justify-center rounded-lg border border-border bg-section px-4 text-center text-sm font-semibold text-muted-foreground hover:bg-background hover:text-foreground"><RiAwardFill className="mr-2 h-6 w-6 text-brand transition-colors group-hover:text-primary" />{item}</div>)}</div></div></section><section className="section-space bg-background"><div className="site-container"><SectionHeading centered title="Trusted by crusher operators across India" /><div className="mt-10 grid grid-cols-2 gap-4 md:grid-cols-6">{Array.from({ length: 6 }, (_, i) => <div key={i} className="flex h-20 items-center justify-center rounded-lg border border-border bg-section text-xs font-semibold text-muted-foreground grayscale transition duration-300 hover:border-brand hover:bg-background hover:grayscale-0">[Client logo]</div>)}</div><div className="mx-auto mt-8 max-w-3xl rounded-lg border border-border border-l-4 border-l-brand bg-background p-7 text-center text-muted-foreground">[Client testimonial]</div></div></section></>; }

export function NetworkNews() { return <section id="news" className="section-space bg-section"><div className="site-container grid gap-12 lg:grid-cols-2"><Reveal><SectionHeading label="Support where it matters" title="Sales & service network" /><div className="mt-8"><NetworkMap /></div></Reveal><Reveal><SectionHeading label="Company updates" title="Latest news" /><div className="mt-8 space-y-4"><NewsCard image={images.newsFinesSeparator} title="New product: Dry fines separator for aggregates, sand and minerals" text="Fine dust raises the water-cement ratio and weakens concrete. This separator removes it without water." /><NewsCard title="Notice of Annual General Meeting" text="Company announcement and meeting notice." /></div></Reveal></div></section>; }

export function NewsCard({ title, text, image }: { title: string; text: string; image?: string }) { return <article className="card-hover hover-nudge group flex gap-5 rounded-lg border border-border bg-background p-5">{image && <ImagePlaceholder image={{ src: image, alt: "", caption: "Photo: news", ratio: "4/3" }} className="hidden w-40 shrink-0 self-start sm:block" />}<div className="min-w-0"><span className="text-xs font-bold text-primary">NEWS</span><h3 className="mt-2 font-display text-lg font-bold leading-7 text-foreground transition-colors group-hover:text-primary">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p><a href="#news" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-primary">Read update <RiArrowRightLine className="nudge h-4 w-4" /></a></div></article>; }



export function EnquirySection() { return <section id="enquiry" className="section-space bg-background"><div className="site-container"><div className="overflow-hidden rounded-lg border border-border border-t-4 border-t-brand bg-background shadow-card"><div className="grid lg:grid-cols-[0.8fr_1.2fr]"><div className="bg-section p-7 md:p-12"><SectionHeading label="Project enquiry" title="Tell us about your project" /><p className="mt-5 text-base leading-7 text-muted-foreground">Share your stone type and required output. Our sales team will recommend the right machine and reply within 24 hours.</p><div className="mt-8 space-y-4 text-sm">{[[RiPhoneFill,"Sales",contact.sales],[RiToolsFill,"Service",contact.service],[RiBuilding2Fill,"Office",contact.office],[RiMailFill,"Email",contact.email]].map(([Icon,label,value]) => { const ContactIcon = Icon as IconType; return <div key={String(label)} className="flex items-start gap-3"><ContactIcon className="mt-0.5 h-5 w-5 text-primary" /><div><span className="block font-bold text-foreground">{String(label)}</span><span className="text-muted-foreground">{String(value)}</span></div></div>; })}</div></div><div className="p-7 md:p-12"><EnquiryForm /></div></div></div></div></section>; }

export function Footer() { return <footer id="contact" className="bg-footer text-footer-foreground"><div className="site-container grid gap-10 py-14 sm:grid-cols-2 lg:grid-cols-4"><div><div className="flex items-center gap-2.5"><img src="/logo-mark-white.png" alt="" className="h-14 w-14 shrink-0" width={56} height={56} /><span className="flex flex-col font-display leading-tight"><span className="text-xl font-bold">Akashganga</span><span className="text-xs font-semibold uppercase tracking-[0.12em] text-footer-muted">Constructional Machines</span></span></div><p className="mt-4 text-sm leading-6 text-footer-muted">Manufacturer of patented VSI crushers, artificial sand making machines and dust separation equipment.</p><p className="mt-4 text-sm leading-6 text-footer-muted">{contact.address}</p></div><FooterLinks title="Machines" links={machineMenu.slice(0,6)} /><FooterLinks title="Company" links={["About", "Technology & Patents", "Profitability", "Gallery", "Careers", "FAQs", "Contact"]} /><div><h3 className="font-display font-bold">Contact</h3><div className="mt-4 space-y-3 text-sm text-footer-muted"><a className="link-sweep w-fit hover:text-footer-foreground" href={`tel:${contact.sales.replaceAll(" ", "")}`}>Sales: {contact.sales}</a><a className="link-sweep w-fit hover:text-footer-foreground" href={`mailto:${contact.email}`}>{contact.email}</a><div className="flex gap-4 pt-2"><a href="#linkedin" aria-label="LinkedIn" className="transition hover:-translate-y-0.5 hover:text-brand"><RiLinkedinFill className="h-5 w-5" /></a><a href="#facebook" aria-label="Facebook" className="transition hover:-translate-y-0.5 hover:text-brand"><RiFacebookFill className="h-5 w-5" /></a></div></div></div></div><div className="border-t border-footer-border"><div className="site-container flex flex-col justify-between gap-3 py-5 text-xs text-footer-muted sm:flex-row"><span>© 2026 Akashganga Constructional Machines Pvt. Ltd. All rights reserved.</span><a href="#privacy">Privacy Policy</a></div></div></footer>; }
function FooterLinks({ title, links }: { title: string; links: readonly string[] }) { return <div><h3 className="font-display font-bold">{title}</h3><ul className="mt-4 space-y-2.5">{links.map((link) => <li key={link}><a href={anchor(link)} className="link-sweep text-sm text-footer-muted hover:text-footer-foreground">{link}</a></li>)}</ul></div>; }

export function HomePage() { return <div className="min-h-screen bg-background"><Header /><main><Hero /><StatsBar /><AboutSection /><MachinesSection /><TechnologySection /><ProcessTimeline /><ApplicationsSection /><ComparisonTable /><ClientsStrip /><NetworkNews /><EnquirySection /></main><Footer /><a href={contact.whatsapp} target="_blank" rel="noreferrer" aria-label="Contact Akashganga on WhatsApp" className="fixed bottom-5 right-5 z-30 flex h-14 w-14 items-center justify-center rounded-full bg-whatsapp text-whatsapp-foreground shadow-float transition duration-300 hover:-translate-y-1 hover:scale-105 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"><RiWhatsappFill className="h-7 w-7" /></a></div>; }

